# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  ################################################
  l2: False
  l2_beta: 0.001
  # l2_model_path: "/home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ_L2_0.001_IMM2/weight_wsj.pt"
  l2_model_path: "/home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ+TED_L2_0.001_IMM2/weight_libri.pt"
  save_weight: False
  # save_weight_path: /home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ_TED_L2_0.001_IMM2/weight_libri.pt
  # save_weight_path: /home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ_TED_L2_0.001_IMM2/weight_wsj.pt
  # save_weight_path: /home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ_TED_L2_0.001_IMM2/weight_ted.pt
  save_weight_path: /home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ+TED_L2_0.001_IMM2/weight_wsjted.pt  
  save_grad: False
  # save_grad_path: /home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ_TED_L2_0.001_IMM2/grad_libri.pt
  # save_grad_path: /home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ_TED_L2_0.001_IMM2/grad_wsj_by_wsj.pt
  # save_grad_path: /home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ_TED_L2_0.001_IMM2/grad_wsj_by_960big.pt
  # save_grad_path: /home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ_TED_L2_0.001_IMM2/grad_ted_by_libri.pt
  # save_grad_path: /home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ_TED_L2_0.001_IMM2/grad_ted_by_wsj.pt
  # save_grad_path: /home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ_TED_L2_0.001_IMM2/grad_ted_by_ted.pt
  # save_grad_path: /home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ+TED_L2_0.001_IMM2/grad_wsjted_by_wsjted.pt
  save_grad_path: /home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ+TED_L2_0.001_IMM2/grad_wsjted_by_libri.pt
  mode_imm: True
  mode_imm_task_num: 2
  # mode_imm_weight_path:  ['//home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ_TED_L2_0.001_IMM2/weight_libri.pt','/home/jpong/HYlab/examples/asr/librispeech//outputs/libri960big_WSJ_TED_L2_0.001_IMM2/weight_wsj.pt','/home/jpong/HYlab/examples/asr/librispeech//outputs/libri960big_WSJ_TED_L2_0.001_IMM2/weight_ted.pt']
  # mode_imm_grad_path: ['/home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ_TED_L2_0.001_IMM2/grad_ted_by_libri.pt','/home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ_TED_L2_0.001_IMM2/grad_ted_by_wsj.pt','/home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ_TED_L2_0.001_IMM2/grad_ted_by_ted.pt']
  # mode_imm_save_model_path: '/home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ_TED_L2_0.001_IMM2/model_IMM_ted_ted_ted.pt'
  mode_imm_weight_path:  ['/home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ+TED_L2_0.001_IMM2/weight_libri.pt','/home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ+TED_L2_0.001_IMM2/weight_wsjted.pt']
  mode_imm_grad_path: ['/home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ+TED_L2_0.001_IMM2/grad_wsjted_by_libri.pt','/home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ+TED_L2_0.001_IMM2/grad_wsjted_by_wsjted.pt']
  mode_imm_save_model_path: '/home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ+TED_L2_0.001_IMM2/model_IMM_wsj+ted.pt'
  imm_fine: False
  imm_fine_model_path: '/home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ_TED_L2_0.001_IMM2/model_IMM__ted_ted_ted.pt'
  ##################################################

checkpoint:
  save_dir: /home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big/checkpoints
  restore_file: /home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big/checkpoints/checkpoint_best.pt
  # save_dir: /home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ_L2_0.001_IMM2/checkpoints
  # restore_file: /home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ_L2_0.001_IMM2/checkpoints/checkpoint_best.pt
  # save_dir: /home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ_TED_L2_0.001_IMM2/checkpoints
  # restore_file: /home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ_TED_L2_0.001_IMM2/checkpoints/checkpoint_best.pt
  # save_dir: /home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ+TED_L2_0.001_IMM2/checkpoints
  # restore_file: /home/jpong/HYlab/examples/asr/librispeech/outputs/libri960big_WSJ+TED_L2_0.001_IMM2/checkpoints/checkpoint_best.pt
  # reset_lr_scheduler: true
  # reset_optimizer: true
  # save_interval: 50 #
  save_interval_updates: 25000
  keep_interval_updates: 1
  no_epoch_checkpoints: true

task:
  _name: audio_pretraining
  data: ???
  max_sample_size: 320000
  min_sample_size: 32000
  normalize: true

dataset:
  num_workers: 6
  max_tokens: 900000
  skip_invalid_size_inputs_valid_test: true

distributed_training:
  distributed_world_size: 128
  ddp_backend: legacy_ddp

criterion:
  _name: wav2vec
  infonce: true
  log_keys: ["prob_perplexity","code_perplexity","temp"]
  loss_weights: [0.1, 0]

optimization:
  # max_epoch: 1074  #
  # max_epoch: 609  #
  max_update: 1500000
  lr: [0.0001]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 32000

model:
  _name: wav2vec2
  quantize_targets: true
  extractor_mode: default   ## change
  # conv_feature_layers: "[(512, 10, 5)] + [(512, 3, 2)] * 4 + [(512, 2, 2)] + [(512, 2, 2)]"  ## change
  # layer_norm_first: true
  final_dim: 768
  # latent_temp: [2.0,0.1,0.999995]
  # encoder_layerdrop: 0.2 
  # dropout_input: 0.0
  # dropout_features: 0.0
  # dropout: 0.0
  # attention_dropout: 0.0
  conv_bias: false   ## change

  encoder_layers: 24
  encoder_embed_dim: 1024
  encoder_ffn_embed_dim: 4096
  encoder_attention_heads: 16

  # feature_
